name: opensourceways Repo Stats

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  call_repo_stats_core:
    uses: ./.github/workflows/repo-stats-core.yml
    with:
      org: opensourceways # 使用输入或默认组织
    secrets:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}