name: opensourceways Repo Stats

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  get_year:
    runs-on: ubuntu-latest
    outputs:
      year: ${{ steps.get_year.outputs.year }}
    steps:
      - name: Get Current Year
        id: get_year
        run: echo "year=$(date +%Y)" >> $GITHUB_OUTPUT
  call_repo_stats_core:
      needs: get_year
      uses: ./.github/workflows/repo-stats-core.yml
      with:
        org:  'opensourceways' # 设置默认组织
        end_year: ${{ needs.get_year.outputs.year }} # 传递计算得到的年份
      secrets: inherit
