name: GitHub Repo Stats

on:
  schedule:
    - cron: '0 0 * * *' # 每天凌晨 0 点运行
  workflow_dispatch: # 手动触发工作流

jobs:
  get_repo_stats:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - run: |
          sudo apt install -y git cloc

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12' # 或其他合适的 Python 版本

      - name: Install dependencies
        run: |
          pip install aiohttp argparse pygit2 tqdm 

      - name: Cache repos
        id: cache-repos
        uses: actions/cache@v3
        with:
          path: opensourceways
          key: opensourceways-repos

      - name: Cache output JSON
        id: cache-output
        uses: actions/cache@v3
        with:
          path: 'opensourceways_*_stats.json' # 缓存所有 JSON 文件
          key: opensourceways-output

      - name: Run script
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # 使用 GitHub 提供的令牌
          ORG_NAME: opensourceways # 替换为你的组织名称
          MAX_CONCURRENCY: 10 # 根据需要调整并发数
        run: |
          python your_script.py -t $ORG_NAME $GITHUB_TOKEN -o opensourceways
          ls -l *.json # 列出生成的 JSON 文件

      - name: Configure Git
        run: |
          git config --global user.name "GitHub Actions Bot"
          git config --global user.email "actions@github.com"
          git add *.json
          git commit -m "Update repo stats JSON file"
          git diff --quiet && git diff --staged --quiet || (git commit -m "Update repos stats" && git push)      
